# Generated by Django 4.0.6 on 2023-01-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=models.CharField(max_length=2000),
        ),
    ]
